# Generated by Django 5.2.4 on 2025-07-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True)),
                ('codice_fiscale', models.CharField(max_length=16)),
                ('ragione_sociale', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=200)),
                ('citta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True)),
                ('data', models.DateField()),
                ('imponibile', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('totale', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Utenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True)),
                ('data_apertura', models.DateField()),
                ('indirizzo', models.CharField(max_length=200)),
                ('citta', models.CharField(max_length=100)),
                ('data_chiusura', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('attivo', 'Attivo'), ('inattivo', 'Inattivo')], max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='una_acies.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Lettura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True)),
                ('data', models.DateField()),
                ('valore', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fattura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='una_acies.fattura')),
                ('utenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='una_acies.utenza')),
            ],
        ),
    ]
