# Generated by Django 5.2.4 on 2025-07-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('una_acies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fattura',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lettura',
            name='id',
        ),
        migrations.RemoveField(
            model_name='utenza',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codice',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='codice',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lettura',
            name='codice',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utenza',
            name='codice',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
